from app.models.school import School
from app.models.user import User
from app.models.student import Student
from app.models.teacher import Teacher
from app.models.attendance import Attendance
from app.models.fee import Fee
from app.models.subject import Subject
from app.models.notice import Notice
from app.models.assignment import Assignment
from app.models.submission import Submission
from app.models.result import Result
from app.models.coursebook import CourseBook
from app.models.timetable import TimetableEntry