"use client";
import { useState } from "react";
import { Download, FileText, Loader2 } from "lucide-react";

interface Props {
  title: string;
  data: Record<string, unknown> | Record<string, unknown>[];
  filename?: string;
}

export default function ExportButton({ title, data, filename }: Props) {
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);

  const rows = Array.isArray(data) ? data : [data];

  const getHeaders = () => {
    if (rows.length === 0) return [];
    return Object.keys(rows[0]);
  };

  const getBaseName = () => filename || title.toLowerCase().replace(/\s+/g, "-");

  const exportCSV = () => {
    setLoading(true);
    try {
      if (rows.length === 0) {
        alert("No data to export");
        return;
      }
      const headers = getHeaders();
      const csvRows = rows.map((row) =>
        headers.map((header) => JSON.stringify(row[header] ?? "")).join(",")
      );
      const csv = [headers.join(","), ...csvRows].join("\n");
      const blob = new Blob([csv], { type: "text/csv" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = getBaseName() + ".csv";
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setLoading(false);
      setOpen(false);
    }
  };

  const buildDocumentHtml = () => {
    if (rows.length === 0) return "";
    const headers = getHeaders();
    const tableRows = rows.map((row) =>
      "<tr>" + headers.map((header) => "<td style='padding:8px 12px;border-bottom:1px solid #e2e8f0;font-size:13px;color:#334155'>" + String(row[header] ?? "") + "</td>").join("") + "</tr>"
    ).join("");
    return `<!DOCTYPE html><html><head><meta charset='UTF-8'><title>${title}</title>
<style>body{font-family:Arial,sans-serif;padding:40px;color:#0f172a}h1{font-size:22px;font-weight:bold;margin-bottom:4px}p{color:#64748b;font-size:13px;margin-bottom:24px}table{width:100%;border-collapse:collapse}th{text-align:left;padding:8px 12px;background:#f8fafc;font-size:12px;color:#64748b;font-weight:500;border-bottom:2px solid #e2e8f0}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:11px;color:#94a3b8}</style></head>
<body><h1>${title}</h1><p>Generated by Nyxion EduOS · ${new Date().toLocaleDateString()}</p>
<table><thead><tr>${headers.map(h => "<th>" + h.replace(/_/g," ").toUpperCase() + "</th>").join("")}</tr></thead>
<tbody>${tableRows}</tbody></table>
<div class='footer'>Nyxion EduOS · nyxion-labs.vercel.app · hello@nyxionlabs.com</div></body></html>`;
  };

  const exportWord = () => {
    setLoading(true);
    try {
      const html = buildDocumentHtml();
      if (!html) { alert("No data"); return; }
      const blob = new Blob([html], { type: "application/msword" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = getBaseName() + ".doc";
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setLoading(false);
      setOpen(false);
    }
  };

  const exportPDF = () => {
    setLoading(true);
    try {
      const html = buildDocumentHtml();
      if (!html) { alert("No data"); return; }
      const printWindow = window.open("", "_blank", "width=960,height=720");
      if (!printWindow) {
        alert("Please allow pop-ups to export PDF.");
        return;
      }
      printWindow.document.open();
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    } finally {
      setLoading(false);
      setOpen(false);
    }
  };

  const exportJSON = () => {
    setLoading(true);
    try {
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = getBaseName() + ".json";
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setLoading(false);
      setOpen(false);
    }
  };

  const printPage = () => {
    window.print();
    setOpen(false);
  };

  return (
    <div className="relative">
      <button onClick={() => setOpen(!open)}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 text-sm font-medium transition-all">
        {loading ? <Loader2 size={16} className="animate-spin"/> : <Download size={16}/>}
        Export
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-2 w-44 bg-white rounded-xl border border-slate-200 shadow-lg z-50 overflow-hidden">
          <button onClick={exportPDF} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-all">
            <FileText size={14} className="text-red-600"/> Export PDF
          </button>
          <button onClick={exportWord} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-all">
            <FileText size={14} className="text-blue-600"/> Export Word
          </button>
          <button onClick={exportCSV} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-all">
            <FileText size={14} className="text-green-600"/> Export CSV
          </button>
          <button onClick={exportJSON} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-all">
            <FileText size={14} className="text-amber-600"/> Export JSON
          </button>
          <button onClick={printPage} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 border-t border-slate-100 transition-all">
            <FileText size={14} className="text-slate-500"/> Print Page
          </button>
        </div>
      )}
      {open && <div className="fixed inset-0 z-40" onClick={()=>setOpen(false)}/>}
    </div>
  );
}
