"use client";
import { useState } from "react";
import { Download, FileText, Loader2 } from "lucide-react";

interface Props {
  title: string;
  data: any;
  filename?: string;
}

export default function ExportButton({ title, data, filename }: Props) {
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);

  const exportCSV = () => {
    setLoading(true);
    try {
      if (!Array.isArray(data) || data.length === 0) {
        alert("No data to export");
        return;
      }
      const headers = Object.keys(data[0]);
      const rows = data.map((row: any) =>
        headers.map(h => JSON.stringify(row[h] ?? "")).join(",")
      );
      const csv = [headers.join(","), ...rows].join("\n");
      const blob = new Blob([csv], { type: "text/csv" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = (filename || title.toLowerCase().replace(/\s+/g,"-")) + ".csv";
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setLoading(false);
      setOpen(false);
    }
  };

  const exportHTML = () => {
    setLoading(true);
    try {
      const rows = Array.isArray(data) ? data : [data];
      if (rows.length === 0) { alert("No data"); return; }
      const headers = Object.keys(rows[0]);
      const tableRows = rows.map(r =>
        "<tr>" + headers.map(h => "<td style='padding:8px 12px;border-bottom:1px solid #e2e8f0;font-size:13px;color:#334155'>" + (r[h] ?? "") + "</td>").join("") + "</tr>"
      ).join("");
      const html = `<!DOCTYPE html><html><head><meta charset='UTF-8'><title>${title}</title>
<style>body{font-family:Arial,sans-serif;padding:40px;color:#0f172a}h1{font-size:22px;font-weight:bold;margin-bottom:4px}p{color:#64748b;font-size:13px;margin-bottom:24px}table{width:100%;border-collapse:collapse}th{text-align:left;padding:8px 12px;background:#f8fafc;font-size:12px;color:#64748b;font-weight:500;border-bottom:2px solid #e2e8f0}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:11px;color:#94a3b8}</style></head>
<body><h1>${title}</h1><p>Generated by Nyxion EduOS · ${new Date().toLocaleDateString()}</p>
<table><thead><tr>${headers.map(h => "<th>" + h.replace(/_/g," ").toUpperCase() + "</th>").join("")}</tr></thead>
<tbody>${tableRows}</tbody></table>
<div class='footer'>Nyxion EduOS · nyxion-labs.vercel.app · hello@nyxionlabs.com</div></body></html>`;
      const blob = new Blob([html], { type: "text/html" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = (filename || title.toLowerCase().replace(/\s+/g,"-")) + ".html";
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setLoading(false);
      setOpen(false);
    }
  };

  const exportJSON = () => {
    setLoading(true);
    try {
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = (filename || title.toLowerCase().replace(/\s+/g,"-")) + ".json";
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setLoading(false);
      setOpen(false);
    }
  };

  const printPage = () => {
    window.print();
    setOpen(false);
  };

  return (
    <div className="relative">
      <button onClick={() => setOpen(!open)}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 text-sm font-medium transition-all">
        {loading ? <Loader2 size={16} className="animate-spin"/> : <Download size={16}/>}
        Export
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-2 w-44 bg-white rounded-xl border border-slate-200 shadow-lg z-50 overflow-hidden">
          <button onClick={exportCSV} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-all">
            <FileText size={14} className="text-green-600"/> Export CSV
          </button>
          <button onClick={exportHTML} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-all">
            <FileText size={14} className="text-blue-600"/> Export HTML (Print)
          </button>
          <button onClick={exportJSON} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 transition-all">
            <FileText size={14} className="text-amber-600"/> Export JSON
          </button>
          <button onClick={printPage} className="flex items-center gap-2 w-full px-4 py-2.5 text-sm text-slate-700 hover:bg-slate-50 border-t border-slate-100 transition-all">
            <FileText size={14} className="text-slate-500"/> Print Page
          </button>
        </div>
      )}
      {open && <div className="fixed inset-0 z-40" onClick={()=>setOpen(false)}/>}
    </div>
  );
}